alias update="sudo aptitude upgrade && sudo aptitude -y safe-upgrade && sudo apt-get -y autoremove && sudo ee update"
alias mc="sudo mc"
alias chubuntu="sudo chown -R ubuntu:ubuntu"
alias chwww="sudo chwon -R www-data:www-data"
alias ll="ls -la"
